name: Unzip Uploaded File

on:
  push:
    paths:
      - '*.zip' # This triggers the workflow only when a .zip file is pushed

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Unzip the file
        run: |
          sudo apt-get install -y unzip
          unzip -o '*.zip' -d ./unzipped_files # Unzips into a directory named 'unzipped_files'
      
      - name: Push unzipped files back to the repository
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Unzipped files"
          git push origin HEAD:main
